version: '3.8'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_INNODB_FAST_SHUTDOWN=0
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./import.sql:/import.sql