version: '3.9'

services:
  app:
    image: cotilen/backend-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: cotilen/banco
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_INNODB_FAST_SHUTDOWN=0
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./import.sql:/docker-entrypoint-initdb.d/import.sql